# -*- coding: utf-8 -*-
"""Assignment-7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ydFJYCjNsmzBAxEGAbG5ZA1G_cm5vdFl
"""

from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import numpy as np
from itertools import product, combinations


fig = plt.figure()
ax = fig.gca(projection='3d')


# draw sphere
u, v = np.mgrid[0:2*np.pi:20j, 0:np.pi:10j]
k=161
r = np.sqrt(k**2-161/4)
x = r*np.cos(u)*np.sin(v)+1
y = r*np.sin(u)*np.sin(v)+3.5
z = r*np.cos(v)-1
ax.plot_wireframe(x, y, z, color="r")

# draw a point
ax.scatter([1], [3.5], [-1], color="g", s=100)



plt.show