# -*- coding: utf-8 -*-
"""Assignment-7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ydFJYCjNsmzBAxEGAbG5ZA1G_cm5vdFl
"""

# import the module
from python import * sphere(center = vector(1,7/2,-1),
radius = sqrt(k*2-161/4),
shininess = 1,
emissive = False)